// keyword: AccountConnection

export const TransactionsPageJSON = {
  data: {
    viewer: {
      id: "VXNlcjozNTE3NjYyNA==",
      transactionCategories: [
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTox",
          __typename: "TransactionCategory",
          type: "default",
          label: "Auto & Transport",
          iconKey: "auto_transport",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(15, 161, 169)",
            faded: "rgba(15, 161, 169, 0.20999999999999996)",
            light: "rgb(18, 193, 203)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToy",
          __typename: "TransactionCategory",
          type: "default",
          label: "Bills & Utilities",
          iconKey: "bills_utilities",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(55, 126, 184)",
            faded: "rgba(55, 126, 184, 0.20999999999999996)",
            light: "rgb(83, 150, 204)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToz",
          __typename: "TransactionCategory",
          type: "default",
          label: "Business",
          iconKey: "business_expense",
          includeInSpending: true,
          includeInEarnings: true,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(102, 166, 30)",
            faded: "rgba(102, 166, 30, 0.20999999999999996)",
            light: "rgb(122, 199, 36)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTo0",
          __typename: "TransactionCategory",
          type: "default",
          label: "Cash & Checks",
          iconKey: "cash_checks",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(46, 168, 109)",
            faded: "rgba(46, 168, 109, 0.20999999999999996)",
            light: "rgb(56, 201, 131)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTozODI0MDA=",
          __typename: "TransactionCategory",
          type: "default",
          label: "Charitable Donations",
          iconKey: "gifts_donations",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: true,
          categoryType: "expense",
          colors: {
            base: "rgb(116, 158, 0)",
            faded: "rgba(116, 158, 0, 0.20999999999999996)",
            light: "rgb(139, 190, 0)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTo0MjE4ODg=",
          __typename: "TransactionCategory",
          type: "default",
          label: "Credit Card Payment",
          iconKey: "credit_card_payment",
          includeInSpending: false,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "ignored",
          colors: {
            base: "rgb(0, 160, 209)",
            faded: "rgba(0, 160, 209, 0.20999999999999996)",
            light: "rgb(0, 192, 251)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTo1",
          __typename: "TransactionCategory",
          type: "default",
          label: "Dining & Drinks",
          iconKey: "dining_drinks",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(85, 105, 216)",
            faded: "rgba(85, 105, 216, 0.20999999999999996)",
            light: "rgb(134, 148, 227)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTo2",
          __typename: "TransactionCategory",
          type: "default",
          label: "Education",
          iconKey: "education",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(217, 95, 2)",
            faded: "rgba(217, 95, 2, 0.20999999999999996)",
            light: "rgb(253, 115, 10)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTo3",
          __typename: "TransactionCategory",
          type: "default",
          label: "Entertainment & Rec.",
          iconKey: "entertainment_recreation",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(230, 115, 0)",
            faded: "rgba(230, 115, 0, 0.20999999999999996)",
            light: "rgb(255, 138, 21)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTo4",
          __typename: "TransactionCategory",
          type: "default",
          label: "Family Care",
          iconKey: "family_care",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(229, 57, 119)",
            faded: "rgba(229, 57, 119, 0.20999999999999996)",
            light: "rgb(236, 108, 154)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTo5",
          __typename: "TransactionCategory",
          type: "default",
          label: "Fees",
          iconKey: "fees",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(255, 0, 0)",
            faded: "rgba(255, 0, 0, 0.20999999999999996)",
            light: "rgb(255, 51, 51)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxMA==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Gifts",
          iconKey: "gift",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(102, 57, 229)",
            faded: "rgba(102, 57, 229, 0.20999999999999996)",
            light: "rgb(141, 108, 236)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxMQ==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Groceries",
          iconKey: "groceries",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(196, 46, 96)",
            faded: "rgba(196, 46, 96, 0.20999999999999996)",
            light: "rgb(213, 77, 123)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxMg==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Health & Wellness",
          iconKey: "health_fitness",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(0, 162, 184)",
            faded: "rgba(0, 162, 184, 0.20999999999999996)",
            light: "rgb(0, 194, 221)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxMw==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Home & Garden",
          iconKey: "home_housing",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(33, 171, 44)",
            faded: "rgba(33, 171, 44, 0.20999999999999996)",
            light: "rgb(40, 205, 53)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTo0Ng==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Ignore",
          iconKey: "ignore",
          includeInSpending: false,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "ignored",
          colors: {
            base: "rgb(51, 51, 51)",
            faded: "rgba(51, 51, 51, 0.20999999999999996)",
            light: "rgb(61, 61, 61)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxNA==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Income",
          iconKey: "income",
          includeInSpending: false,
          includeInEarnings: true,
          taxDeductible: false,
          categoryType: "earning",
          colors: {
            base: "rgb(63, 162, 145)",
            faded: "rgba(63, 162, 145, 0.20999999999999996)",
            light: "rgb(82, 188, 170)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToyMw==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Internal Transfers",
          iconKey: "transfer",
          includeInSpending: false,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "ignored",
          colors: {
            base: "rgb(117, 117, 117)",
            faded: "rgba(117, 117, 117, 0.20999999999999996)",
            light: "rgb(140, 140, 140)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxNQ==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Investment",
          iconKey: "investment",
          includeInSpending: false,
          includeInEarnings: true,
          taxDeductible: false,
          categoryType: "earning",
          colors: {
            base: "rgb(24, 165, 109)",
            faded: "rgba(24, 165, 109, 0.20999999999999996)",
            light: "rgb(29, 198, 131)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxNg==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Legal",
          iconKey: "legal",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(250, 99, 82)",
            faded: "rgba(250, 99, 82, 0.20999999999999996)",
            light: "rgb(252, 157, 147)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxNw==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Loan Payment",
          iconKey: "loan_repayment",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(92, 154, 199)",
            faded: "rgba(92, 154, 199, 0.20999999999999996)",
            light: "rgb(135, 181, 214)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToyNzczMw==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Medical",
          iconKey: "medical",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(0, 126, 242)",
            faded: "rgba(0, 126, 242, 0.20999999999999996)",
            light: "rgb(35, 150, 255)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxOQ==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Personal Care",
          iconKey: "personal_care",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(247, 101, 167)",
            faded: "rgba(247, 101, 167, 0.20999999999999996)",
            light: "rgb(250, 167, 205)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToyMA==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Pets",
          iconKey: "pets",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(18, 159, 202)",
            faded: "rgba(18, 159, 202, 0.20999999999999996)",
            light: "rgb(29, 187, 235)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxMjAzMA==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Reimbursement",
          iconKey: "reimbursement",
          includeInSpending: false,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "ignored",
          colors: {
            base: "rgb(0, 126, 242)",
            faded: "rgba(0, 126, 242, 0.20999999999999996)",
            light: "rgb(35, 150, 255)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTo0MjE4ODU=",
          __typename: "TransactionCategory",
          type: "default",
          label: "Savings Transfer",
          iconKey: "savings_transfer",
          includeInSpending: false,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "ignored",
          colors: {
            base: "rgb(98, 165, 44)",
            faded: "rgba(98, 165, 44, 0.20999999999999996)",
            light: "rgb(118, 198, 53)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToyMQ==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Shopping",
          iconKey: "shopping",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(194, 139, 0)",
            faded: "rgba(194, 139, 0, 0.20999999999999996)",
            light: "rgb(233, 167, 0)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeTo1MTY2MzE=",
          __typename: "TransactionCategory",
          type: "default",
          label: "Software & Tech",
          iconKey: "software",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(18, 95, 196)",
            faded: "rgba(18, 95, 196, 0.20999999999999996)",
            light: "rgb(23, 114, 234)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToyMg==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Taxes",
          iconKey: "taxes",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(23, 48, 73)",
            faded: "rgba(23, 48, 73, 0.20999999999999996)",
            light: "rgb(28, 58, 88)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToyNA==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Travel & Vacation",
          iconKey: "travel_vacation",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "expense",
          colors: {
            base: "rgb(252, 96, 49)",
            faded: "rgba(252, 96, 49, 0.20999999999999996)",
            light: "rgb(253, 142, 108)",
            __typename: "Colors",
          },
        },
        {
          id: "VHJhbnNhY3Rpb25DYXRlZ29yeToxOA==",
          __typename: "TransactionCategory",
          type: "default",
          label: "Uncategorized",
          iconKey: "other",
          includeInSpending: true,
          includeInEarnings: false,
          taxDeductible: false,
          categoryType: "no_category_type",
          colors: {
            base: "rgb(28, 122, 249)",
            faded: "rgba(28, 122, 249, 0.20999999999999996)",
            light: "rgb(82, 154, 250)",
            __typename: "Colors",
          },
        },
      ],
      accounts: {
        edges: [
          {
            node: {
              id: "QWNjb3VudDo0MDUwOTAyMjE=",
              name: "Apple Card",
              number: "0000",
              enabled: true,
              applicable: true,
              institution: {
                __typename: "Institution",
                id: "SW5zdGl0dXRpb246MTM4MjY5",
                name: "Apple Card",
                icon_url:
                  "https://truebill-logos.s3.amazonaws.com/institution-logos/apple_card_csv_black.png?resolve=true",
                short_name: "Apple Card",
                light_color: "#F0F0F0",
                primary_color: "#000000",
              },
              __typename: "Account",
            },
            __typename: "AccountEdge",
          },
          {
            node: {
              id: "QWNjb3VudDo0MDUwOTA3ODc=",
              name: "Delta SkyMiles® Gold Card",
              number: "1003",
              enabled: true,
              applicable: true,
              institution: {
                __typename: "Institution",
                id: "SW5zdGl0dXRpb246Ng==",
                name: "American Express",
                icon_url:
                  "https://d3ld0h2wcl5cud.cloudfront.net/ins_10/logo?resolve=true",
                short_name: "American Express",
                light_color: "#3d96df",
                primary_color: "#007cc3",
              },
              __typename: "Account",
            },
            __typename: "AccountEdge",
          },
          {
            node: {
              id: "QWNjb3VudDo0MDUwOTczMDU=",
              name: "KYLE AULT 606 W 1720 N APT 340 PROVO UT 84604-2481",
              number: "4094",
              enabled: true,
              applicable: true,
              institution: {
                __typename: "Institution",
                id: "SW5zdGl0dXRpb246MTM5ODE1",
                name: "Pershing Investments - NetXInvestor",
                icon_url: null,
                short_name: "Pershing Investments - NetXInvestor",
                light_color: null,
                primary_color: "#0075a3",
              },
              __typename: "Account",
            },
            __typename: "AccountEdge",
          },
          {
            node: {
              id: "QWNjb3VudDo0MDUwOTc2NzA=",
              name: "META PLATFORMS, INC. 401(K) PLAN",
              number: "7536",
              enabled: true,
              applicable: true,
              institution: {
                __typename: "Institution",
                id: "SW5zdGl0dXRpb246MTUzNzc3",
                name: "Fidelity",
                icon_url:
                  "https://d15e55tqlrbrds.cloudfront.net/institution-logos/institution-logo-Fidelity-1707424072259.png?resolve=true",
                short_name: "Fidelity",
                light_color: null,
                primary_color: null,
              },
              __typename: "Account",
            },
            __typename: "AccountEdge",
          },
          {
            node: {
              id: "QWNjb3VudDo0MDUwOTA4Mjc=",
              name: "Personal Profile",
              number: null,
              enabled: true,
              applicable: true,
              institution: {
                __typename: "Institution",
                id: "SW5zdGl0dXRpb246MTQwNzUy",
                name: "Venmo - Personal",
                icon_url:
                  "https://d3ld0h2wcl5cud.cloudfront.net/ins_132083/logo?resolve=true",
                short_name: "Venmo - Personal",
                light_color: null,
                primary_color: "#0075a3",
              },
              __typename: "Account",
            },
            __typename: "AccountEdge",
          },
          {
            node: {
              id: "QWNjb3VudDo0MDUwOTAxOTI=",
              name: "Rewards Extra",
              number: "5531",
              enabled: true,
              applicable: true,
              institution: {
                __typename: "Institution",
                id: "SW5zdGl0dXRpb246MTMxMzE2",
                name: "Renasant Bank - Personal",
                icon_url:
                  "https://d3ld0h2wcl5cud.cloudfront.net/ins_113439/logo?resolve=true",
                short_name: "Renasant Bank - Personal",
                light_color: "#28617f",
                primary_color: "#004966",
              },
              __typename: "Account",
            },
            __typename: "AccountEdge",
          },
          {
            node: {
              id: "QWNjb3VudDo0MDUwOTA4NjI=",
              name: "Robinhood Brokerage",
              number: "8444",
              enabled: true,
              applicable: true,
              institution: {
                __typename: "Institution",
                id: "SW5zdGl0dXRpb246MTMzNjUy",
                name: "Robinhood",
                icon_url:
                  "https://d3ld0h2wcl5cud.cloudfront.net/ins_54/logo?resolve=true",
                short_name: "Robinhood",
                light_color: null,
                primary_color: "#005f32",
              },
              __typename: "Account",
            },
            __typename: "AccountEdge",
          },
          {
            node: {
              id: "QWNjb3VudDo0MDUwOTc2NzE=",
              name: "ROTH IRA",
              number: "2244",
              enabled: true,
              applicable: true,
              institution: {
                __typename: "Institution",
                id: "SW5zdGl0dXRpb246MTUzNzc3",
                name: "Fidelity",
                icon_url:
                  "https://d15e55tqlrbrds.cloudfront.net/institution-logos/institution-logo-Fidelity-1707424072259.png?resolve=true",
                short_name: "Fidelity",
                light_color: null,
                primary_color: null,
              },
              __typename: "Account",
            },
            __typename: "AccountEdge",
          },
        ],
        __typename: "AccountConnection",
      },
      numTransactions: 2838,
      __typename: "User",
    },
  },
};
