services:
  solvers-be:
    build: 
      context: ..
      dockerfile: deploy/Dockerfile.be
    ports:
      - "1213:1213"
    healthcheck:
      test: "curl -f http://localhost:1213/health || exit 1"
      interval: 10s
      timeout: 3s
      retries: 5
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /code
  # redis:
  #   image: "redis:alpine"