services:
  solvers-be:
    build: 
      context: ../server
      dockerfile: deploy/Dockerfile.be
    ports:
      - "1213:1213"
    # develop:
    #   watch:
    #     - action: sync
    #       path: .
    #       target: /code
  # redis:
  #   image: "redis:alpine"